### ISSUE TITLE
Sanity checking of inputs on account creation

### ISSUE THREAD

**Issue by Eve-Nayret** [KryptedGaming/krypted#280]
Usernames currently cannot contain spaces, however, both of these were allowed but encounter a 500 on login and can't do anything until you clear cookies:
`<script>alert('hello');</script>`
`drop;`

More than likely someone would bump a key on create and not realize it. That will be a pain since you can't change / fix without admin intervention. The same is true if you type your email in wrong. Your username will be tied up with the typo'd email without a way to correct (because of the email verification link).

Personally, ditch usernames altogether if you're asking for email address. Primary character name is likely enough for people and they can be just user #### until that is set. Nothing stops someone from being annoying and registering existing users usernames so they have to use something different which would be super annoying to deal with.

Otherwise username regex along these lines... 
`^[\p{L}\p{M}\_\-\.]*$`

Emails currently don't allow '+' which is a valid email character (see gmail) and only have an allowed length of 64, which is technically too short. Currently errors with "Email is required" when a '+' is used. The local part can be 64 characters + domain and other junk. 

While we're at it... age is allowed to be set as negative in the selection. min should be 0 I guess??? (I'd like to meet that newborn baby trying to register...) Maybe consider asking for year of birth instead? A little more annoying to deal with but if you're storing it anywhere could be useful for stats (since age changes over time)

**Comment by porowns** [comment]
I don't think that age is stored, I'd have to check. It's mostly for an 18+ check.

Usernames not having spaces was part of the legacy authentication (causes problems with Discourse package), I should probably change that back. Usernames are used across Django so I wouldn't be comfortable not having them filled out.

**Comment by porowns** [comment]
Unable to replicate the spacing issue. 

Case 1: User bumps space on username at the beginning 
The username removes pre-trailing whitespace

Case 2: User bumps space on username at the end 
The username removes trailing whitespace

Case 3: Space in username (e.g "My User")
Won't allow user to create account. Message is displayed
