### ISSUE TITLE
Add module to add timers to timerboards automatically

### ISSUE THREAD

**Issue by Sjolus** [KryptedGaming/krypted#283]
**Is your feature request related to a problem? Please describe.**
As a corporation our structures get attacked every now and then. It's very sad and adding timers for it manually makes us very sad :( Adding them automatically through the ESI scopes already added to users (as long as we've got directors or structure managers added) should be possible.

The same thing goes for moon extractions, they should also be there. Maybe moon extractions should be a separate module with separate permissions as it can also contain the moon contents.

**Comment by porowns** [comment]
Moved to https://github.com/KryptedGaming/django-eveonline-timerboard/issues/3
