### ISSUE TITLE
Timestamp on timerboard has hardcoded format

### ISSUE THREAD

**Issue by Sjolus** [KryptedGaming/krypted#285]
It should follow the usual Django formatting template logic.

If I could choose, I'd request it to be [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Dates) compliant. 

![ISO 8601](https://imgs.xkcd.com/comics/iso_8601.png)

**Comment by porowns** [comment]
grumble grumble america

**Comment by porowns** [comment]
Fixed in https://github.com/KryptedGaming/django-eveonline-timerboard/commit/b61bf8c9908a93ba81764469ca41f994a12396b6
