### ISSUE TITLE
Make Group States interact with corp standings

### ISSUE THREAD

**Issue by cyruskurush** [KryptedGaming/krypted#289]
For example, say I want to give corps that im blue with access to comms channels, they can log in via krypted auth, join the requisite group and be able to join opsec comms #

**Comment by porowns** [comment]
This would be a good first issue for anyone interested in tackling it. 


## Prerequisite
https://github.com/KryptedGaming/django-eveonline-connector
The base EVE online connector would need to be updated with an ESI call for standings. See examples in https://github.com/KryptedGaming/django-eveonline-connector/tree/master/django_eveonline_connector/services/esi

## Extending the State Package
https://github.com/KryptedGaming/django-eveonline-group-states
GroupStates would need a new boolean flag on the model (check the `models.py`) to toggle standings automation, along with a choice field for red, orange, neutral, etc. 

After that, a task (check `tasks.py`) would need to be created that adds all of the corporations/alliance as qualifiers for that state.

BONUS POINTS: Add characters as an option for states.

**Comment by porowns** [comment]
Moved to new feature: https://github.com/KryptedGaming/django-eveonline-connector/issues/11
