### ISSUE TITLE
Ability for user ESI data to be segregated based on groups

### ISSUE THREAD

**Issue by cyruskurush** [KryptedGaming/krypted#290]
For example, recruits will have no default groups and will have their ESI viewable in one pool, whereas corp members will have group X and have their ESI viewable in a different pool. This would allow for recruiters to do preliminary screening of new candidates, but not be able to see the ESI data of full members, whereas full members can only be viewable by officers

**Comment by porowns** [comment]
Redefined as a feature: https://github.com/KryptedGaming/django-eveonline-connector/issues/12
