### ISSUE TITLE
Ability to set Groups based on in game corp rights/roles/titles

### ISSUE THREAD

**Issue by cyruskurush** [KryptedGaming/krypted#292]
The ability to give auth'd users groups based off what titles/rights are given in game. Example: Ability for a newly promoted FC to be given FC roles on auth, and by extension discord because they had been promoted in game. Cuts down on need to fiddle in the back to promote people and eases first time set up. Also related to this request: #289

**Comment by porowns** [comment]
Moved to new feature: https://github.com/KryptedGaming/django-eveonline-connector/issues/11
