### ISSUE TITLE
Gated Questions for surveys

### ISSUE THREAD

**Issue by cyruskurush** [KryptedGaming/krypted#298]
allow for if certain answers are given, certain questions can be skipped or become available. Example, if someone says they have cruiser V, allow for a question to appear that asks what logistics cruisers they can fly. Or if someone says their favourite activity is mining, allow for the application to end right there.

**Comment by porowns** [comment]
Likely too advanced to be finished anytime soon.

**Comment by porowns** [comment]
Closing, not in the scope of the project. Google form support may be important to investigate.
