### ISSUE TITLE
Allow for incorporation of discord webhooks

### ISSUE THREAD

**Issue by cyruskurush** [KryptedGaming/krypted#301]
Would be useful to ping for timers/new recruits etc

**Comment by porowns** [comment]
What do you mean by this? Do you just want messages for pings?

**Comment by cyruskurush** [comment]
Yes, for stuff like timers or new application submissions

Sent from my iPhone

On Feb 10, 2020, at 13:03, Kaleb <notifications@github.com> wrote:

﻿

What do you mean by this? Do you just want messages for pings?

**Comment by porowns** [comment]
Duplicate https://github.com/KryptedGaming/krypted/issues/287
